### ISSUE TITLE
ADL Data State URI is changing

### ISSUE THREAD

**Issue by creighton** [adlnet/SCORM-to-xAPI-Wrapper#11]
I'm not sure if you deal with ADL Data, but we're changing the RDF uri for the property.

**Comment by jono-poltrack** [comment]
ex. new id would be https://w3id.org/xapi/scorm/attempt-state

Note: I may have done this already, so just search for these IDs.  Might be done.

**Comment by ljwolford** [comment]
looks like this id is already listed in there. closing
