### ISSUE TITLE
xapiwrapper.min.js not found

### ISSUE THREAD

**Issue by claudiogb21** [adlnet/SCORM-to-xAPI-Wrapper#9]
Hi!

I was trying to download the xapiwrapper.min.js from "https://github.com/adlnet/xAPIWrapper/blob/master/xapiwrapper.min.js" but it seems to be lost, and github shows me a 404 error. Can you please fix this?

Thanks!

**Comment by rchadwic** [comment]
I'm not sure that's the right link. Are you looking for 

https://raw.githubusercontent.com/adlnet/xAPIWrapper/master/dist/xapiwrapper.min.js  ?

**Comment by claudiogb21** [comment]
Yes!! That was what i needed! Thanks.

**Comment by rchadwic** [comment]
No prob!
